version: "3.8"
services:
  app:
    build:
      context: .
    restart: always
    networks:
      - internal
      - nginx-load-balancer
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - PORT=3000
      # Needed for CORS on server side requests
      - ORIGIN=${CORS_ORIGIN:-*}
networks:
  internal:
  # On a local machine, create this network befor running the container
    # docker network create -d bridge  docker_nginx-load-balancer
  nginx-load-balancer:
    external: true
    name: docker_nginx-load-balancer
